### ISSUE TITLE
Search plugins in folder one level up

### ISSUE THREAD

**Issue by hghristov** [demsking/gulp-web-dependencies#2]
Hello,

Related to my [issue](https://github.com/demsking/gulp-html-dependencies/issues/3) in gulp-html-dependencies, how does the `folders` option work?

I've tried `folders: '../bower_components'`, `folders: '../'`, `folders: '\/\.\.\/bower_components',` and `folders: '\.\.\/',` and it doesn't seem to work. The plugin is still searching for files in `/src/bower_components`, while my bower_components folder is on the same level as `/src`.

Quoting the issue:

> Hello. 
> 
> I'm using PHP and I've put parts of my project into a `partials/` folder, and I'm getting the following error:
> 
> > Error: ENOENT: no such file or directory, open '[..]project\src\bower_components\jquery\dist\jquery.js'
> 
> My relevant project structure is as follows:
> 
> ```
> project/
> ├── bower_components
> ├── dist
> ├── node_modules
> ├── src
> │   ├── index.php
> │   └──  partials
> │       ├── header.php
> │       └── footer.php
> ```
> 
> The link to jquery in my footer partial is as follows:
> `<script src="../bower_components/jquery/dist/jquery.js"></script>`
> 
> The problem is since I'm using PHP and including my partial in my index file that's located in `project/src/` I need to make the url link only one level up like this `../bower_components` instead of two levels `../../bower_components`. 
> 
> gulp-html-dependencies is looking for `bower_components` in my `src/` folder which is why I'm getting the error, but I need it to search one more level up.
> 
> Is there a way to do this? Perhaps an option to prepend a `../` string to each file before handling it?

Thank you.

**Comment by tavurth** [comment]
Hey @hghristov,

`bower_components` should be included by default, as we can see from the regexp:
```re
        ...${userFolders}bower_components|node_modules...
```

I wrote the folders extension because I wanted to include files from a folder other than `bower_components` or `node_modules`.

My gulp config looks like this:

```javascript
        let path_dest = './dist/app';
        gulp.src('app/index.html') // (app is src for you)
            .pipe(dependencies({
                
                // The basedir of your application. default: path.dirname(file.path)
                dest: path_dest,

                // Which searches in the /project folder for libraries/
                folders: 'libraries',
                
                // The exported URL prefix. Default "/"
                prefix: '/vendor' 
            }))
            .pipe(gulp.dest(path_dest))
```

Which then drops dependencies into my `/dist/app/vendors` directory, and generates the `/dist/app/index.html`
